### ISSUE TITLE
Documentation on Installation

### ISSUE THREAD

**Issue by iraycd** [danpozmanter/jawaf#1]
Missing documentation on how to install.

**Comment by danpozmanter** [comment]
Thanks!! I'll try to get to this tomorrow. For the moment though the way to install is via `python3 setup.py install` from the top directory (ideally within a virtualenv). Eventually you'll be able to run `pip install jawaf` once I feel it's stable enough to submit to pypi.

Of note - you'll need python 3.6+ installed.

**Comment by danpozmanter** [comment]
Added! http://jawaf.readthedocs.io/en/latest/guides/getting_started.html#installing-jawaf
